import wordpress from '@wordpress/eslint-plugin';

export default [
	{
		ignores: [
			'**/node_modules/**',
			'**/dist/**',
			'**/dist-ssr/**',
			'**/build/**',
			'**/build-types/**',
			'**/storybook-static/**',
			'**/*.tsbuildinfo',
			'**/convex/_generated/**',
			'tickets/**',
			'catalog-steps/**',
			'connector-steps/**',
			'/scripts/**',
			'convex_backend/**',
			'.claude/worktrees/**',
			// Gitignored data dumps and scratch fixtures, not source.
			'packages/catalog/data/**',
			'**/*.local/**',
			// Regenerated by `bun run spec`, in its own JSON.stringify style.
			'packages/catalog-portal/src/generated/catalog-api-spec.json',
		],
	},
	...wordpress.configs.recommended,
	{
		rules: {
			// No @wordpress/i18n usage in this repo, so the i18n rule family is dead weight.
			'@wordpress/valid-sprintf': 'off',
			'@wordpress/i18n-translator-comments': 'off',
			'@wordpress/i18n-text-domain': 'off',
			'@wordpress/i18n-no-collapsible-whitespace': 'off',
			'@wordpress/i18n-no-placeholders-only': 'off',
			'@wordpress/i18n-no-variables': 'off',
			'@wordpress/i18n-ellipsis': 'off',
			'@wordpress/i18n-no-flanking-whitespace': 'off',
			'@wordpress/i18n-hyphenated-range': 'off',

			// Team policy: code reads without comments, so JSDoc isn't required.
			'jsdoc/require-jsdoc': 'off',
			'jsdoc/require-param': 'off',
			'jsdoc/require-param-description': 'off',
			'jsdoc/require-param-name': 'off',
			'jsdoc/require-param-type': 'off',
			'jsdoc/require-property': 'off',
			'jsdoc/require-property-description': 'off',
			'jsdoc/require-property-name': 'off',
			'jsdoc/require-property-type': 'off',
			'jsdoc/require-returns': 'off',
			'jsdoc/require-returns-check': 'off',
			'jsdoc/require-returns-description': 'off',
			'jsdoc/require-returns-type': 'off',
			'jsdoc/require-yields': 'off',

			// This repo doesn't use the WordPress-core "External dependencies" docblock convention.
			'@wordpress/dependency-group': 'off',

			// The import resolver can't see bun workspace or TS project-reference imports, and tsc already enforces this.
			'import/no-unresolved': 'off',
			'import/named': 'off',
			'import/default': 'off',
			'import/no-extraneous-dependencies': 'off',
		},
	},
	{
		files: [ 'tools/**', 'packages/*/scripts/**' ],
		rules: { 'no-console': 'off' },
	},
];
