import wordpress from '@wordpress/eslint-plugin';

export default [
	{
		ignores: [
			'**/node_modules/**',
			'**/dist/**',
			'**/dist-ssr/**',
			'**/build/**',
			'**/build-types/**',
			'**/storybook-static/**',
			'**/*.tsbuildinfo',
			'**/convex/_generated/**',
			'tickets/**',
			'catalog-steps/**',
			'connector-steps/**',
			'/scripts/**',
			'convex_backend/**',
			'.claude/worktrees/**',
			// Data dumps / scratch fixtures — gitignored, not source.
			'packages/catalog/data/**',
			'**/*.local/**',
			// Regenerated by `bun run spec`, in its own JSON.stringify style.
			'packages/catalog-portal/src/generated/catalog-api-spec.json',
		],
	},
	...wordpress.configs.recommended,
	{
		rules: {
			// This isn't WordPress core: nothing here ships translations through
			// @wordpress/i18n, so the whole i18n rule family is dead weight.
			'@wordpress/valid-sprintf': 'off',
			'@wordpress/i18n-translator-comments': 'off',
			'@wordpress/i18n-text-domain': 'off',
			'@wordpress/i18n-no-collapsible-whitespace': 'off',
			'@wordpress/i18n-no-placeholders-only': 'off',
			'@wordpress/i18n-no-variables': 'off',
			'@wordpress/i18n-ellipsis': 'off',
			'@wordpress/i18n-no-flanking-whitespace': 'off',
			'@wordpress/i18n-hyphenated-range': 'off',

			// Team policy: code reads without comments, so nothing should demand
			// JSDoc. `recommended` pulls in eslint-plugin-jsdoc's rules through
			// its es5 config, which leaves several of these on by default.
			'jsdoc/require-jsdoc': 'off',
			'jsdoc/require-param': 'off',
			'jsdoc/require-param-description': 'off',
			'jsdoc/require-param-name': 'off',
			'jsdoc/require-param-type': 'off',
			'jsdoc/require-property': 'off',
			'jsdoc/require-property-description': 'off',
			'jsdoc/require-property-name': 'off',
			'jsdoc/require-property-type': 'off',
			'jsdoc/require-returns': 'off',
			'jsdoc/require-returns-check': 'off',
			'jsdoc/require-returns-description': 'off',
			'jsdoc/require-returns-type': 'off',
			'jsdoc/require-yields': 'off',

			// Inserts an "External dependencies" docblock above import groups —
			// a WordPress-core convention this repo doesn't follow. Not wired into
			// `recommended` as of v27, but disabled explicitly in case that changes.
			'@wordpress/dependency-group': 'off',

			// The import resolver can't see bun workspace packages (their
			// "exports" point straight at .ts source, not a build output) or this
			// repo's TS project-reference graph, so it misreports real workspace
			// imports as unresolved. TypeScript already enforces this.
			'import/no-unresolved': 'off',
			'import/named': 'off',
			'import/default': 'off',
			'import/no-extraneous-dependencies': 'off',
		},
	},
	{
		files: [ 'tools/**', 'packages/*/scripts/**' ],
		rules: { 'no-console': 'off' },
	},
];
